name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64
      - name: Setup environment
        uses: ./actions/setup-environment
      - name: Run nox
        run: poetry run nox -s isort black
  static-type-analysis:
    name: Static type analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64
      - name: Setup environment
        uses: ./actions/setup-environment
      - name: Run nox
        run: poetry run nox -s mypy
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64
      - name: Setup environment
        uses: ./actions/setup-environment
      - name: Run nox
        run: poetry run nox -s tests
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64
      - name: Setup
        uses: ./actions/setup-environment
      - name: Run nox
        run: poetry run nox -s lint
