name: Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Build and publish release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Setup environment
        uses: ./actions/setup-environment
      - name: Run nox
        run: poetry run nox
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
