name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install GDAL 3.4.0
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install -y libgdal-dev=3.4.0+dfsg-1~focal0
    - name: Install nox
      run: python -m pip install nox==2021.6.12
    - name: Install poetry
      run: python -m pip install poetry==1.1.13
    - name: Install nox-poetry
      run: python -m pip install nox-poetry==0.9.0
    - name: Run nox
      run: nox
    - name: Build
      run: poetry build
    - name: Publish
      run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
